apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vp-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 3.144.162.185
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vp-app-service
            port:
              name: http
 