apiVersion: apps/v1
kind: Deployment
metadata:
  name: vp-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vp-app
  template:
    metadata:
      labels:
        app: vp-app
    spec:
      containers:
      - name: vp-app
        image: ahmedmohsen98/vp-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB-URL
          valueFrom:
            configMapKeyRef:
              name: vp-configmap
              key: mysql-url
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: vp-secret
              key: mqsql-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: vp-secret
              key: mysql-user
        - name: Rabmq-URL
          valueFrom:
            configMapKeyRef:
              name: vp-configmap
              key: rabmq-url
        - name: memc-URL
          valueFrom:
            configMapKeyRef:
              name: vp-configmap
              key: memc-url  
      
---
apiVersion: v1
kind: Service
metadata:
  name: vp-app-service
spec:
  selector:
    app: vp-app
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP


        